spring.application.name=virgo_back
pje.endpoints.trf1-primeiro-grau=https://pje1g.trf1.jus.br/pje/intercomunicacao
pje.endpoints.trf1-segundo-grau=https://pje2g.trf1.jus.br/pje/intercomunicacao
pje.endpoints.trf6-primeiro-grau=https://pje1g.trf6.jus.br/pje/intercomunicacao
pje.endpoints.trf6-segundo-grau=https://pje2g.trf6.jus.br/pje/intercomunicacao
pje.connect-timeout=5s
pje.read-timeout=30s